/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FilesDividersPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  dividers: [],
  dividerColor: "#484848",
  dividerThickness: 1,
  labelColor: "#888888",
  labelFontSize: 11,
  labelUppercase: true,
  labelBold: true,
  labelItalic: false,
  enabled: true
};
function escapeForCss(str) {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\A ");
}
var FilesDividersPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("minus", "Toggle files dividers", () => {
      this.toggleDividers();
    });
    this.addCommand({
      id: "toggle-files-dividers",
      name: "Toggle files dividers on/off",
      callback: () => {
        this.toggleDividers();
      }
    });
    this.addCommand({
      id: "clear-all-dividers",
      name: "Clear all files dividers",
      callback: () => {
        this.clearAllDividers();
      }
    });
    this.addSettingTab(new FilesDividersSettingTab(this.app, this));
    if (this.settings.enabled) {
      this.applyDividers();
    }
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        if (this.settings.enabled) {
          setTimeout(() => this.applyDividers(), 100);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFolder || file instanceof import_obsidian.TFile) {
          menu.addSeparator();
          const itemType = file instanceof import_obsidian.TFolder ? "folder" : "file";
          const itemName = file.name;
          const existingAbove = this.settings.dividers.find(
            (d) => d.itemName === itemName && d.itemType === itemType && d.position === "above"
          );
          const existingBelow = this.settings.dividers.find(
            (d) => d.itemName === itemName && d.itemType === itemType && d.position === "below"
          );
          if (existingAbove) {
            menu.addItem((item) => {
              item.setTitle(existingAbove.label ? `Remove labeled divider above ("${existingAbove.label}")` : "Remove divider above").setIcon("x").onClick(() => {
                this.removeDividerFromItem(itemName, itemType, "above");
              });
            });
          } else {
            menu.addItem((item) => {
              item.setTitle("Add divider above").setIcon("minus").onClick(() => {
                this.addDividerToItem(itemName, itemType, "above");
              });
            });
            menu.addItem((item) => {
              item.setTitle("Add labeled divider above\u2026").setIcon("text-cursor-input").onClick(() => {
                this.promptAndAddLabeledDivider(itemName, itemType, "above");
              });
            });
          }
          if (existingBelow) {
            menu.addItem((item) => {
              item.setTitle(existingBelow.label ? `Remove labeled divider below ("${existingBelow.label}")` : "Remove divider below").setIcon("x").onClick(() => {
                this.removeDividerFromItem(itemName, itemType, "below");
              });
            });
          } else {
            menu.addItem((item) => {
              item.setTitle("Add divider below").setIcon("minus").onClick(() => {
                this.addDividerToItem(itemName, itemType, "below");
              });
            });
            menu.addItem((item) => {
              item.setTitle("Add labeled divider below\u2026").setIcon("text-cursor-input").onClick(() => {
                this.promptAndAddLabeledDivider(itemName, itemType, "below");
              });
            });
          }
          if (existingAbove || existingBelow) {
            menu.addItem((item) => {
              item.setTitle("Remove all dividers").setIcon("trash").onClick(() => {
                this.removeDividersFromItem(itemName, itemType);
              });
            });
          }
        }
      })
    );
  }
  onunload() {
    this.removeDividers();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.settings.enabled) {
      this.applyDividers();
    } else {
      this.removeDividers();
    }
  }
  addDividerToItem(itemName, itemType, position, label, labelStyle) {
    const exists = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (exists) {
      new import_obsidian.Notice(`Divider already exists ${position} ${itemType} "${itemName}"`);
      return;
    }
    const divider = {
      itemName,
      itemType,
      position,
      style: "line"
    };
    if (label && label.trim()) {
      divider.label = label.trim();
      divider.labelStyle = labelStyle != null ? labelStyle : "above";
    }
    this.settings.dividers.push(divider);
    this.saveSettings();
    const labelPart = divider.label ? ` ("${divider.label}")` : "";
    new import_obsidian.Notice(`Added divider${labelPart} ${position} ${itemType} "${itemName}"`);
  }
  promptAndAddLabeledDivider(itemName, itemType, position) {
    new LabelInputModal(this.app, "", "above", (label, labelStyle) => {
      if (label === null) return;
      this.addDividerToItem(itemName, itemType, position, label, labelStyle);
    }).open();
  }
  updateDividerStyle(itemName, itemType, position, labelStyle) {
    const divider = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (!divider) return;
    divider.labelStyle = labelStyle;
    this.saveSettings();
  }
  updateDividerColor(itemName, itemType, position, field, value) {
    const divider = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (!divider) return;
    if (value === null || value === "") {
      delete divider[field];
    } else {
      divider[field] = value;
    }
    this.saveSettings();
  }
  updateDividerLabel(itemName, itemType, position, label) {
    const divider = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (!divider) return;
    const trimmed = label.trim();
    if (trimmed) {
      divider.label = trimmed;
    } else {
      delete divider.label;
    }
    this.saveSettings();
  }
  removeDividerFromItem(itemName, itemType, position) {
    const before = this.settings.dividers.length;
    this.settings.dividers = this.settings.dividers.filter(
      (d) => !(d.itemName === itemName && d.itemType === itemType && d.position === position)
    );
    if (this.settings.dividers.length < before) {
      this.saveSettings();
      new import_obsidian.Notice(`Removed divider ${position} ${itemType} "${itemName}"`);
    }
  }
  removeDividersFromItem(itemName, itemType) {
    const removedCount = this.settings.dividers.length;
    this.settings.dividers = this.settings.dividers.filter(
      (d) => !(d.itemName === itemName && d.itemType === itemType)
    );
    const newCount = this.settings.dividers.length;
    if (removedCount > newCount) {
      this.saveSettings();
      new import_obsidian.Notice(`Removed ${removedCount - newCount} divider(s) from ${itemType} "${itemName}"`);
    }
  }
  clearAllDividers() {
    if (this.settings.dividers.length === 0) {
      new import_obsidian.Notice("No dividers to clear");
      return;
    }
    const count = this.settings.dividers.length;
    this.settings.dividers = [];
    this.saveSettings();
    new import_obsidian.Notice(`Cleared ${count} divider(s)`);
  }
  applyDividers() {
    this.removeDividers();
    if (this.settings.dividers.length === 0) {
      return;
    }
    const cssRules = this.settings.dividers.map((divider) => {
      var _a;
      const pseudoElement = divider.position === "above" ? "before" : "after";
      const itemClass = divider.itemType === "folder" ? "nav-folder" : "nav-file";
      const selectorBase = `.${itemClass}-divider-${divider.position}[data-item="${escapeForCss(divider.itemName)}"][data-type="${divider.itemType}"]`;
      if (divider.label) {
        const edge = divider.position === "above" ? "top" : "bottom";
        const marginSide = divider.position === "above" ? "margin-top" : "margin-bottom";
        const transform = this.settings.labelUppercase ? "uppercase" : "none";
        const letterSpacing = this.settings.labelUppercase ? "0.08em" : "normal";
        const fontWeight = this.settings.labelBold ? "600" : "400";
        const fontStyle = this.settings.labelItalic ? "italic" : "normal";
        const effectiveLabelColor = divider.labelColor || this.settings.labelColor;
        const effectiveLineColor = divider.lineColor || this.settings.dividerColor;
        const labelStyle = (_a = divider.labelStyle) != null ? _a : "above";
        if (labelStyle === "centered") {
          const stripeOffset = Math.max(10, this.settings.labelFontSize);
          const totalSpacing2 = stripeOffset + this.settings.labelFontSize / 2 + 4;
          return `
                        /* --- Centered labeled divider for ${divider.itemType} "${divider.itemName}" --- */
                        ${selectorBase} {
                            position: relative;
                            ${marginSide}: ${totalSpacing2}px;
                        }

                        ${selectorBase}::after {
                            content: '';
                            position: absolute;
                            ${edge}: -${stripeOffset}px;
                            left: 0;
                            right: 0;
                            width: 100%;
                            height: ${this.settings.dividerThickness}px;
                            background-color: ${effectiveLineColor};
                            border-radius: ${this.settings.dividerThickness / 2}px;
                            opacity: 0.7;
                            pointer-events: none;
                            z-index: 1;
                        }

                        ${selectorBase}::before {
                            content: "${escapeForCss(divider.label)}";
                            position: absolute;
                            ${edge}: -${stripeOffset + this.settings.labelFontSize / 2}px;
                            left: 50%;
                            transform: translateX(-50%);
                            color: ${effectiveLabelColor};
                            font-size: ${this.settings.labelFontSize}px;
                            font-weight: ${fontWeight};
                            font-style: ${fontStyle};
                            text-transform: ${transform};
                            letter-spacing: ${letterSpacing};
                            line-height: 1;
                            padding: 0 8px;
                            background-color: var(--background-secondary, var(--background-primary, #1e1e1e));
                            opacity: 0.95;
                            pointer-events: none;
                            white-space: nowrap;
                            z-index: 2;
                        }
                    `;
        }
        const lineOffset = 6;
        const labelOffset = lineOffset + this.settings.labelFontSize + 8;
        const totalSpacing = labelOffset + 6;
        return `
                    /* --- Labeled divider (above-style) for ${divider.itemType} "${divider.itemName}" --- */
                    ${selectorBase} {
                        position: relative;
                        ${marginSide}: ${totalSpacing}px;
                    }

                    ${selectorBase}::before {
                        content: "${escapeForCss(divider.label)}";
                        position: absolute;
                        ${edge}: -${labelOffset}px;
                        left: 0;
                        right: 0;
                        width: 100%;
                        box-sizing: border-box;
                        color: ${effectiveLabelColor};
                        font-size: ${this.settings.labelFontSize}px;
                        font-weight: ${fontWeight};
                        font-style: ${fontStyle};
                        text-transform: ${transform};
                        letter-spacing: ${letterSpacing};
                        line-height: 1.2;
                        padding: 0 6px;
                        opacity: 0.95;
                        pointer-events: none;
                    }

                    ${selectorBase}::after {
                        content: '';
                        position: absolute;
                        ${edge}: -${lineOffset}px;
                        left: 0;
                        right: 0;
                        width: 100%;
                        height: ${this.settings.dividerThickness}px;
                        background-color: ${effectiveLineColor};
                        border-radius: ${this.settings.dividerThickness / 2}px;
                        opacity: 0.7;
                        pointer-events: none;
                    }
                `;
      }
      return `
                /* --- Divider styles for files and folders --- */
                ${selectorBase}::${pseudoElement} {
                    content: '';
                    position: absolute;
                    left: 0;
                    right: 0;
                    width: 100%;
                    height: ${this.settings.dividerThickness}px;
                    background-color: ${this.settings.dividerColor};
                    border-radius: ${this.settings.dividerThickness / 2}px;
                    opacity: 0.6;
                    ${divider.position === "above" ? `top: -${8 + this.settings.dividerThickness}px;` : `bottom: -${8 + this.settings.dividerThickness}px;`}
                }

                /* --- Add spacing and position to dividers --- */
                ${selectorBase} {
                    position: relative;
                    ${divider.position === "above" ? "margin-top: 16px;" : "margin-bottom: 16px;"}
                }
            `;
    }).join("\n");
    const styleElement = document.createElement("style");
    styleElement.id = "files-dividers-styles";
    styleElement.textContent = cssRules;
    document.head.appendChild(styleElement);
    this.addDividerClasses();
  }
  addDividerClasses() {
    const fileExplorer = document.querySelector(".nav-files-container");
    if (!fileExplorer) return;
    document.querySelectorAll("[data-item]").forEach((el) => {
      el.removeAttribute("data-item");
      el.removeAttribute("data-type");
      el.classList.remove("nav-folder-divider-above");
      el.classList.remove("nav-folder-divider-below");
      el.classList.remove("nav-file-divider-above");
      el.classList.remove("nav-file-divider-below");
    });
    this.settings.dividers.forEach((divider) => {
      if (divider.itemType === "folder") {
        const folders = fileExplorer.querySelectorAll(".nav-folder");
        folders.forEach((folder) => {
          var _a;
          const titleElement = folder.querySelector(".nav-folder-title");
          if (titleElement) {
            const folderName = (_a = titleElement.textContent) == null ? void 0 : _a.trim();
            if (folderName === divider.itemName) {
              folder.classList.add(`nav-folder-divider-${divider.position}`);
              folder.setAttribute("data-item", divider.itemName);
              folder.setAttribute("data-type", "folder");
            }
          }
        });
      } else if (divider.itemType === "file") {
        const files = fileExplorer.querySelectorAll(".nav-file");
        files.forEach((file) => {
          var _a;
          const titleElement = file.querySelector(".nav-file-title");
          if (titleElement) {
            const fileName = (_a = titleElement.textContent) == null ? void 0 : _a.trim();
            const fileNameWithoutExt = fileName == null ? void 0 : fileName.replace(/\.[^/.]+$/, "");
            const dividerNameWithoutExt = divider.itemName.replace(/\.[^/.]+$/, "");
            if (fileName === divider.itemName || fileNameWithoutExt === dividerNameWithoutExt || fileName === dividerNameWithoutExt || fileNameWithoutExt === divider.itemName) {
              file.classList.add(`nav-file-divider-${divider.position}`);
              file.setAttribute("data-item", divider.itemName);
              file.setAttribute("data-type", "file");
            }
          }
        });
      }
    });
  }
  removeDividers() {
    const existingStyles = document.getElementById("files-dividers-styles");
    if (existingStyles) {
      existingStyles.remove();
    }
    document.querySelectorAll("[data-item]").forEach((el) => {
      el.removeAttribute("data-item");
      el.removeAttribute("data-type");
      el.removeClass("nav-folder-divider-above");
      el.removeClass("nav-folder-divider-below");
      el.removeClass("nav-file-divider-above");
      el.removeClass("nav-file-divider-below");
    });
  }
  toggleDividers() {
    this.settings.enabled = !this.settings.enabled;
    this.saveSettings();
    const status = this.settings.enabled ? "enabled" : "disabled";
    new import_obsidian.Notice(`Files dividers ${status}`);
  }
};
var FilesDividersSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Labeled Dividers" });
    new import_obsidian.Setting(containerEl).setName("Enable files dividers").setDesc("Turn dividers on or off globally for both files and folders").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Divider color").setDesc("Color of the divider lines").addColorPicker(
      (color) => color.setValue(this.plugin.settings.dividerColor).onChange(async (value) => {
        this.plugin.settings.dividerColor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Divider thickness").setDesc("Thickness of divider lines in pixels").addSlider(
      (slider) => slider.setLimits(1, 5, 1).setValue(this.plugin.settings.dividerThickness).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.dividerThickness = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Label styling" });
    new import_obsidian.Setting(containerEl).setName("Label color").setDesc("Color of section-label text on labeled dividers").addColorPicker(
      (color) => color.setValue(this.plugin.settings.labelColor).onChange(async (value) => {
        this.plugin.settings.labelColor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Label font size").setDesc("Size of label text in pixels").addSlider(
      (slider) => slider.setLimits(8, 18, 1).setValue(this.plugin.settings.labelFontSize).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.labelFontSize = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Uppercase labels").setDesc("Render labels in UPPERCASE with slight letter-spacing (section-header style)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.labelUppercase).onChange(async (value) => {
        this.plugin.settings.labelUppercase = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Bold labels").setDesc("Render label text in bold weight").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.labelBold).onChange(async (value) => {
        this.plugin.settings.labelBold = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Italic labels").setDesc("Render label text in italics").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.labelItalic).onChange(async (value) => {
        this.plugin.settings.labelItalic = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "How to use" });
    containerEl.createEl("p", {
      text: 'Right-click any file or folder in the file explorer. Pick "Add divider above/below" for a plain line, or "Add labeled divider above/below\u2026" to attach a section name. Labels render as small section-header text with a line beneath (or above, if positioned below).'
    });
    containerEl.createEl("h3", { text: "Current Dividers" });
    if (this.plugin.settings.dividers.length === 0) {
      containerEl.createEl("p", {
        text: "No dividers configured. Right-click on files or folders to add dividers.",
        cls: "setting-item-description"
      });
    } else {
      const folderDividers = this.plugin.settings.dividers.filter((d) => d.itemType === "folder");
      const fileDividers = this.plugin.settings.dividers.filter((d) => d.itemType === "file");
      const renderDividerRow = (divider, emoji) => {
        var _a;
        const labelDisplay = divider.label ? `"${divider.label}"` : "(no label)";
        const styleDisplay = divider.label ? ` \xB7 ${(_a = divider.labelStyle) != null ? _a : "above"}` : "";
        const setting = new import_obsidian.Setting(containerEl).setName(`${emoji} ${divider.itemName}`).setDesc(`Divider ${divider.position} \u2014 ${labelDisplay}${styleDisplay}`);
        setting.addText(
          (text) => {
            var _a2;
            return text.setPlaceholder("Section label (blank for plain line)").setValue((_a2 = divider.label) != null ? _a2 : "").onChange(async (value) => {
              this.plugin.updateDividerLabel(divider.itemName, divider.itemType, divider.position, value);
            });
          }
        );
        if (divider.label) {
          setting.addDropdown(
            (dropdown) => {
              var _a2;
              return dropdown.addOption("above", "Above").addOption("centered", "Centered \u2500x\u2500").setValue((_a2 = divider.labelStyle) != null ? _a2 : "above").onChange(async (value) => {
                this.plugin.updateDividerStyle(divider.itemName, divider.itemType, divider.position, value);
                this.display();
              });
            }
          );
        }
        setting.addButton(
          (button) => button.setButtonText("Remove").setWarning().onClick(async () => {
            const globalIndex = this.plugin.settings.dividers.indexOf(divider);
            this.plugin.settings.dividers.splice(globalIndex, 1);
            await this.plugin.saveSettings();
            this.display();
          })
        );
        const advancedRow = containerEl.createDiv();
        advancedRow.style.display = "flex";
        advancedRow.style.gap = "12px";
        advancedRow.style.alignItems = "center";
        advancedRow.style.fontSize = "12px";
        advancedRow.style.opacity = "0.75";
        advancedRow.style.marginBottom = "14px";
        advancedRow.style.marginLeft = "24px";
        const labelColorWrap = advancedRow.createDiv();
        labelColorWrap.style.display = "flex";
        labelColorWrap.style.alignItems = "center";
        labelColorWrap.style.gap = "4px";
        labelColorWrap.createSpan({ text: "Label color override:" });
        const labelColorInput = labelColorWrap.createEl("input", { type: "color" });
        labelColorInput.value = divider.labelColor || this.plugin.settings.labelColor;
        labelColorInput.title = divider.labelColor ? "Override active \u2014 clear to use global" : "Using global color";
        labelColorInput.addEventListener("change", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "labelColor", labelColorInput.value);
        });
        const labelClearBtn = labelColorWrap.createEl("button", { text: "\xD7" });
        labelClearBtn.title = "Clear override (use global label color)";
        labelClearBtn.style.padding = "0 6px";
        labelClearBtn.style.minHeight = "0";
        labelClearBtn.addEventListener("click", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "labelColor", null);
          this.display();
        });
        const lineColorWrap = advancedRow.createDiv();
        lineColorWrap.style.display = "flex";
        lineColorWrap.style.alignItems = "center";
        lineColorWrap.style.gap = "4px";
        lineColorWrap.createSpan({ text: "Line color override:" });
        const lineColorInput = lineColorWrap.createEl("input", { type: "color" });
        lineColorInput.value = divider.lineColor || this.plugin.settings.dividerColor;
        lineColorInput.title = divider.lineColor ? "Override active \u2014 clear to use global" : "Using global color";
        lineColorInput.addEventListener("change", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "lineColor", lineColorInput.value);
        });
        const lineClearBtn = lineColorWrap.createEl("button", { text: "\xD7" });
        lineClearBtn.title = "Clear override (use global line color)";
        lineClearBtn.style.padding = "0 6px";
        lineClearBtn.style.minHeight = "0";
        lineClearBtn.addEventListener("click", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "lineColor", null);
          this.display();
        });
      };
      if (folderDividers.length > 0) {
        containerEl.createEl("h4", { text: "Folder Dividers" });
        folderDividers.forEach((divider) => renderDividerRow(divider, "\u{1F4C1}"));
      }
      if (fileDividers.length > 0) {
        containerEl.createEl("h4", { text: "File Dividers" });
        fileDividers.forEach((divider) => renderDividerRow(divider, "\u{1F4C4}"));
      }
      new import_obsidian.Setting(containerEl).addButton(
        (button) => button.setButtonText("Clear all dividers").setWarning().onClick(async () => {
          this.plugin.clearAllDividers();
          this.display();
        })
      );
    }
  }
};
var LabelInputModal = class extends import_obsidian.Modal {
  constructor(app, initialValue, initialStyle, callback) {
    super(app);
    this.settled = false;
    this.initialValue = initialValue;
    this.initialStyle = initialStyle;
    this.chosenStyle = initialStyle;
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Section label" });
    contentEl.createEl("p", {
      text: "Enter the section text. Leave blank to cancel.",
      cls: "setting-item-description"
    });
    const input = contentEl.createEl("input", { type: "text" });
    input.value = this.initialValue;
    input.placeholder = "e.g. PROJECTS";
    input.style.width = "100%";
    input.style.marginBottom = "12px";
    const styleLabel = contentEl.createEl("div", { text: "Label style" });
    styleLabel.style.fontWeight = "500";
    styleLabel.style.marginBottom = "4px";
    const styleRow = contentEl.createDiv();
    styleRow.style.display = "flex";
    styleRow.style.gap = "16px";
    styleRow.style.marginBottom = "14px";
    const makeRadio = (value, labelText, descText) => {
      const wrap = styleRow.createEl("label");
      wrap.style.display = "flex";
      wrap.style.alignItems = "flex-start";
      wrap.style.gap = "6px";
      wrap.style.cursor = "pointer";
      const radio = wrap.createEl("input", { type: "radio" });
      radio.name = "labeled-divider-style";
      radio.value = value;
      radio.checked = this.chosenStyle === value;
      radio.addEventListener("change", () => {
        if (radio.checked) this.chosenStyle = value;
      });
      const labelWrap = wrap.createDiv();
      const titleEl = labelWrap.createEl("div", { text: labelText });
      titleEl.style.fontSize = "13px";
      const descEl = labelWrap.createEl("div", { text: descText });
      descEl.style.fontSize = "11px";
      descEl.style.opacity = "0.7";
    };
    makeRadio("above", "Above", "Text sits above the line");
    makeRadio("centered", "Centered", "\u2500\u2500\u2500 TEXT \u2500\u2500\u2500 (line through label)");
    const buttonRow = contentEl.createDiv();
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "flex-end";
    buttonRow.style.gap = "8px";
    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    const submitBtn = buttonRow.createEl("button", { text: "Add divider", cls: "mod-cta" });
    input.focus();
    input.select();
    const submit = () => {
      const value = input.value.trim();
      if (!value) {
        this.settle(null);
      } else {
        this.settle(value);
      }
      this.close();
    };
    const cancel = () => {
      this.settle(null);
      this.close();
    };
    submitBtn.addEventListener("click", submit);
    cancelBtn.addEventListener("click", cancel);
    input.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        evt.preventDefault();
        submit();
      } else if (evt.key === "Escape") {
        evt.preventDefault();
        cancel();
      }
    });
  }
  onClose() {
    if (!this.settled) {
      this.callback(null, this.chosenStyle);
      this.settled = true;
    }
    this.contentEl.empty();
  }
  settle(value) {
    if (this.settled) return;
    this.settled = true;
    this.callback(value, this.chosenStyle);
  }
};
