/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FilesDividersPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var LABEL_STYLE_OPTIONS = [
  { value: "above", letter: "A", title: "Above-style (default)", desc: "Label hugs the file, thin line below as section boundary" },
  { value: "centered", letter: "B", title: "Centered through line", desc: "\u2500\u2500\u2500\u2500 LABEL \u2500\u2500\u2500\u2500 line passes through the label" },
  { value: "chip", letter: "C", title: "Pill / chip", desc: "Compact rounded chip + thin line beside it" },
  { value: "underline", letter: "D", title: "Underline only", desc: "Label with thin underline, no separate line" },
  { value: "section", letter: "E", title: "Section header", desc: "Filled background + left accent bar \u2014 strongest grouping" },
  { value: "minimal", letter: "F", title: "Notion-style minimal", desc: "Small muted label, no caps, subtle line" },
  { value: "tucked", letter: "G", title: "Bold accent + tucked", desc: "Thick colored line with small label tucked top-right" },
  { value: "gradient", letter: "H", title: "Soft gradient bar", desc: "Gradient fades through label color, no hard line" }
];
var DEFAULT_SETTINGS = {
  dividers: [],
  dividerColor: "#484848",
  dividerThickness: 1,
  labelColor: "#888888",
  labelFontSize: 11,
  labelUppercase: true,
  labelBold: true,
  labelItalic: false,
  enabled: true
};
function dividerKey(itemName, itemType, position) {
  return `${itemType}::${position}::${itemName}`;
}
var FilesDividersPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.applyDebounce = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("minus", "Toggle files dividers", () => {
      this.toggleDividers();
    });
    this.addCommand({
      id: "toggle-files-dividers",
      name: "Toggle files dividers on/off",
      callback: () => {
        this.toggleDividers();
      }
    });
    this.addCommand({
      id: "clear-all-dividers",
      name: "Clear all files dividers",
      callback: () => {
        this.clearAllDividers();
      }
    });
    this.addSettingTab(new FilesDividersSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.enabled) {
        this.applyDividers();
      }
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        if (this.settings.enabled) {
          this.scheduleApply();
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFolder || file instanceof import_obsidian.TFile) {
          menu.addSeparator();
          const itemType = file instanceof import_obsidian.TFolder ? "folder" : "file";
          const itemName = file.name;
          const existingAbove = this.settings.dividers.find(
            (d) => d.itemName === itemName && d.itemType === itemType && d.position === "above"
          );
          const existingBelow = this.settings.dividers.find(
            (d) => d.itemName === itemName && d.itemType === itemType && d.position === "below"
          );
          if (existingAbove) {
            menu.addItem((item) => {
              item.setTitle(existingAbove.label ? `Edit label above ("${existingAbove.label}")\u2026` : "Add label to divider above\u2026").setIcon("text-cursor-input").onClick(() => {
                this.promptAndEditLabel(existingAbove);
              });
            });
            menu.addItem((item) => {
              item.setTitle(existingAbove.label ? `Remove labeled divider above ("${existingAbove.label}")` : "Remove divider above").setIcon("x").onClick(() => {
                this.removeDividerFromItem(itemName, itemType, "above");
              });
            });
          } else {
            menu.addItem((item) => {
              item.setTitle("Add divider above").setIcon("minus").onClick(() => {
                this.addDividerToItem(itemName, itemType, "above");
              });
            });
            menu.addItem((item) => {
              item.setTitle("Add labeled divider above\u2026").setIcon("text-cursor-input").onClick(() => {
                this.promptAndAddLabeledDivider(itemName, itemType, "above");
              });
            });
          }
          if (existingBelow) {
            menu.addItem((item) => {
              item.setTitle(existingBelow.label ? `Edit label below ("${existingBelow.label}")\u2026` : "Add label to divider below\u2026").setIcon("text-cursor-input").onClick(() => {
                this.promptAndEditLabel(existingBelow);
              });
            });
            menu.addItem((item) => {
              item.setTitle(existingBelow.label ? `Remove labeled divider below ("${existingBelow.label}")` : "Remove divider below").setIcon("x").onClick(() => {
                this.removeDividerFromItem(itemName, itemType, "below");
              });
            });
          } else {
            menu.addItem((item) => {
              item.setTitle("Add divider below").setIcon("minus").onClick(() => {
                this.addDividerToItem(itemName, itemType, "below");
              });
            });
            menu.addItem((item) => {
              item.setTitle("Add labeled divider below\u2026").setIcon("text-cursor-input").onClick(() => {
                this.promptAndAddLabeledDivider(itemName, itemType, "below");
              });
            });
          }
          if (existingAbove || existingBelow) {
            menu.addItem((item) => {
              item.setTitle("Remove all dividers").setIcon("trash").onClick(() => {
                this.removeDividersFromItem(itemName, itemType);
              });
            });
          }
        }
      })
    );
  }
  onunload() {
    if (this.applyDebounce !== null) {
      window.clearTimeout(this.applyDebounce);
      this.applyDebounce = null;
    }
    this.removeDividers();
  }
  scheduleApply() {
    if (this.applyDebounce !== null) {
      window.clearTimeout(this.applyDebounce);
    }
    this.applyDebounce = window.setTimeout(() => {
      this.applyDebounce = null;
      this.applyDividers();
    }, 150);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.settings.enabled) {
      this.applyDividers();
    } else {
      this.removeDividers();
    }
  }
  addDividerToItem(itemName, itemType, position, label, labelStyle) {
    const exists = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (exists) {
      new import_obsidian.Notice(`Divider already exists ${position} ${itemType} "${itemName}"`);
      return;
    }
    const divider = {
      itemName,
      itemType,
      position,
      style: "line"
    };
    if (label && label.trim()) {
      divider.label = label.trim();
      divider.labelStyle = labelStyle != null ? labelStyle : "above";
    }
    this.settings.dividers.push(divider);
    this.saveSettings();
    const labelPart = divider.label ? ` ("${divider.label}")` : "";
    new import_obsidian.Notice(`Added divider${labelPart} ${position} ${itemType} "${itemName}"`);
  }
  promptAndAddLabeledDivider(itemName, itemType, position) {
    new LabelInputModal(this.app, "", "above", (label, labelStyle) => {
      if (label === null) return;
      this.addDividerToItem(itemName, itemType, position, label, labelStyle);
    }).open();
  }
  promptAndEditLabel(divider) {
    var _a, _b;
    const currentLabel = (_a = divider.label) != null ? _a : "";
    const currentStyle = (_b = divider.labelStyle) != null ? _b : "above";
    new LabelInputModal(this.app, currentLabel, currentStyle, (label, labelStyle) => {
      if (label === null) return;
      divider.label = label;
      divider.labelStyle = labelStyle;
      this.saveSettings();
      new import_obsidian.Notice(`Updated label to "${label}" (${labelStyle})`);
    }).open();
  }
  updateDividerStyle(itemName, itemType, position, labelStyle) {
    const divider = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (!divider) return;
    divider.labelStyle = labelStyle;
    this.saveSettings();
  }
  updateDividerColor(itemName, itemType, position, field, value) {
    const divider = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (!divider) return;
    if (value === null || value === "") {
      delete divider[field];
    } else {
      divider[field] = value;
    }
    this.saveSettings();
  }
  updateDividerLabel(itemName, itemType, position, label) {
    const divider = this.settings.dividers.find(
      (d) => d.itemName === itemName && d.itemType === itemType && d.position === position
    );
    if (!divider) return;
    const trimmed = label.trim();
    if (trimmed) {
      divider.label = trimmed;
    } else {
      delete divider.label;
    }
    this.saveSettings();
  }
  removeDividerFromItem(itemName, itemType, position) {
    const before = this.settings.dividers.length;
    this.settings.dividers = this.settings.dividers.filter(
      (d) => !(d.itemName === itemName && d.itemType === itemType && d.position === position)
    );
    if (this.settings.dividers.length < before) {
      this.saveSettings();
      new import_obsidian.Notice(`Removed divider ${position} ${itemType} "${itemName}"`);
    }
  }
  removeDividersFromItem(itemName, itemType) {
    const removedCount = this.settings.dividers.length;
    this.settings.dividers = this.settings.dividers.filter(
      (d) => !(d.itemName === itemName && d.itemType === itemType)
    );
    const newCount = this.settings.dividers.length;
    if (removedCount > newCount) {
      this.saveSettings();
      new import_obsidian.Notice(`Removed ${removedCount - newCount} divider(s) from ${itemType} "${itemName}"`);
    }
  }
  clearAllDividers() {
    if (this.settings.dividers.length === 0) {
      new import_obsidian.Notice("No dividers to clear");
      return;
    }
    const count = this.settings.dividers.length;
    this.settings.dividers = [];
    this.saveSettings();
    new import_obsidian.Notice(`Cleared ${count} divider(s)`);
  }
  /**
   * applyDividers — DOM-based rendering.
   * Removes any previously-injected divider elements + style sheets, then for every
   * configured divider finds the matching file/folder row and inserts a real <div>
   * sibling (before for above-position, after for below). Each div is fully styled
   * via CSS classes (one per labelStyle) and a CSS custom-property block for
   * per-divider color overrides.
   *
   * Real DOM (vs. earlier pseudo-element approach) means:
   *   - no fighting with theme's overflow:hidden on .nav-file rows
   *   - 8 visually-distinct styles can each define their own internal markup
   *   - future wishlist item #13 (click label to edit) is unlocked
   */
  applyDividers(retriesLeft = 5) {
    this.removeDividers();
    this.installStyles();
    if (this.settings.dividers.length === 0) return;
    const fileExplorer = document.querySelector(".nav-files-container");
    if (!fileExplorer) {
      if (retriesLeft > 0) {
        window.setTimeout(() => this.applyDividers(retriesLeft - 1), 200);
      }
      return;
    }
    this.settings.dividers.forEach((divider) => {
      const anchor = this.findAnchor(fileExplorer, divider);
      if (!anchor) return;
      const dividerEl = this.createDividerEl(divider);
      const parent = anchor.parentNode;
      if (!parent) return;
      if (divider.position === "above") {
        parent.insertBefore(dividerEl, anchor);
      } else {
        parent.insertBefore(dividerEl, anchor.nextSibling);
      }
    });
  }
  /**
   * Locate the .nav-folder / .nav-file element that matches a divider's anchor name.
   * For files we accept name-with-extension and name-without-extension on either side
   * (the explorer DOM strips extensions for visible titles in some Obsidian configs).
   */
  findAnchor(container, divider) {
    var _a, _b;
    const itemClass = divider.itemType === "folder" ? "nav-folder" : "nav-file";
    const titleClass = divider.itemType === "folder" ? "nav-folder-title" : "nav-file-title";
    const candidates = container.querySelectorAll(`.${itemClass}`);
    for (let i = 0; i < candidates.length; i++) {
      const candidate = candidates[i];
      const titleEl = candidate.querySelector(`.${titleClass}`);
      if (!titleEl) continue;
      const name = (_b = (_a = titleEl.textContent) == null ? void 0 : _a.trim()) != null ? _b : "";
      if (divider.itemType === "file") {
        const nameNoExt = name.replace(/\.[^/.]+$/, "");
        const targetNoExt = divider.itemName.replace(/\.[^/.]+$/, "");
        if (name === divider.itemName || nameNoExt === targetNoExt || name === targetNoExt || nameNoExt === divider.itemName) {
          return candidate;
        }
      } else if (name === divider.itemName) {
        return candidate;
      }
    }
    return null;
  }
  /**
   * Build the divider's HTMLElement for the appropriate style.
   * Each style defines its own internal markup; CSS classes from installStyles()
   * paint the look. Per-divider colors flow through CSS custom properties so
   * overrides don't require new style rules.
   */
  createDividerEl(divider) {
    var _a, _b;
    const labelText = ((_a = divider.label) != null ? _a : "").trim();
    const style = (_b = divider.labelStyle) != null ? _b : "above";
    const labelColor = divider.labelColor || this.settings.labelColor;
    const lineColor = divider.lineColor || this.settings.dividerColor;
    const container = document.createElement("div");
    container.classList.add("lbl-div");
    container.classList.add(`lbl-div--pos-${divider.position}`);
    container.classList.add(labelText ? `lbl-div--${style}` : "lbl-div--plain");
    container.setAttribute("data-key", dividerKey(divider.itemName, divider.itemType, divider.position));
    container.style.setProperty("--lbl-div-label-color", labelColor);
    container.style.setProperty("--lbl-div-line-color", lineColor);
    container.style.setProperty("--lbl-div-thickness", `${this.settings.dividerThickness}px`);
    container.style.setProperty("--lbl-div-font-size", `${this.settings.labelFontSize}px`);
    container.style.setProperty("--lbl-div-font-weight", this.settings.labelBold ? "600" : "400");
    container.style.setProperty("--lbl-div-font-style", this.settings.labelItalic ? "italic" : "normal");
    container.style.setProperty("--lbl-div-text-transform", this.settings.labelUppercase ? "uppercase" : "none");
    container.style.setProperty("--lbl-div-letter-spacing", this.settings.labelUppercase ? "0.08em" : "normal");
    if (!labelText) {
      const line = document.createElement("div");
      line.className = "lbl-div__line";
      container.appendChild(line);
      return container;
    }
    const mkEl = (tag, cls, text) => {
      const el = document.createElement(tag);
      el.className = cls;
      if (text !== void 0) el.textContent = text;
      return el;
    };
    switch (style) {
      case "centered":
        container.append(
          mkEl("div", "lbl-div__line-side"),
          mkEl("span", "lbl-div__label", labelText),
          mkEl("div", "lbl-div__line-side")
        );
        break;
      case "chip":
        container.append(
          mkEl("span", "lbl-div__chip", labelText),
          mkEl("div", "lbl-div__line-thin")
        );
        break;
      case "underline":
        container.append(mkEl("span", "lbl-div__label-underline", labelText));
        break;
      case "section":
        container.append(
          mkEl("div", "lbl-div__bar"),
          mkEl("span", "lbl-div__label", labelText)
        );
        break;
      case "minimal":
        container.append(
          mkEl("div", "lbl-div__label-soft", labelText),
          mkEl("div", "lbl-div__line-soft")
        );
        break;
      case "tucked":
        container.append(
          mkEl("span", "lbl-div__label-tuck", labelText),
          mkEl("div", "lbl-div__line-thick")
        );
        break;
      case "gradient":
        container.append(mkEl("div", "lbl-div__label-bar", labelText));
        break;
      case "above":
      default:
        container.append(
          mkEl("div", "lbl-div__label", labelText),
          mkEl("div", "lbl-div__line")
        );
        break;
    }
    return container;
  }
  /**
   * Inject the single base stylesheet covering all 8 label styles + plain dividers.
   * Idempotent — reuses the existing <style id="lbl-div-styles"> if already attached.
   */
  installStyles() {
    let styleEl = document.getElementById("lbl-div-styles");
    if (!styleEl) {
      styleEl = document.createElement("style");
      styleEl.id = "lbl-div-styles";
      document.head.appendChild(styleEl);
    }
    styleEl.textContent = `
.lbl-div { display: block; user-select: none; pointer-events: none; }
.lbl-div__label, .lbl-div__label-soft, .lbl-div__label-underline,
.lbl-div__label-tuck, .lbl-div__label-bar, .lbl-div__chip {
    color: var(--lbl-div-label-color, #888);
    font-size: var(--lbl-div-font-size, 11px);
    font-weight: var(--lbl-div-font-weight, 600);
    font-style: var(--lbl-div-font-style, normal);
    text-transform: var(--lbl-div-text-transform, uppercase);
    letter-spacing: var(--lbl-div-letter-spacing, 0.08em);
    line-height: 1.2;
}
.lbl-div__line, .lbl-div__line-side, .lbl-div__line-thin,
.lbl-div__line-soft, .lbl-div__line-thick {
    background-color: var(--lbl-div-line-color, #484848);
    border-radius: 1px;
}

/* Plain divider */
.lbl-div--plain { padding: 6px 0; }
.lbl-div--plain .lbl-div__line {
    height: var(--lbl-div-thickness, 1px);
    margin: 0 12px;
    opacity: 0.7;
}

/* A \u2014 Above-style (default) */
.lbl-div--above { padding: 6px 0 4px; }
.lbl-div--above .lbl-div__label { padding: 0 12px; }
.lbl-div--above .lbl-div__line {
    height: var(--lbl-div-thickness, 1px);
    margin: 4px 12px 0;
    opacity: 0.7;
}

/* B \u2014 Centered through line */
.lbl-div--centered {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 16px;
}
.lbl-div--centered .lbl-div__line-side {
    flex: 1;
    height: var(--lbl-div-thickness, 1px);
    opacity: 0.7;
}
.lbl-div--centered .lbl-div__label { white-space: nowrap; }

/* C \u2014 Pill / chip */
.lbl-div--chip {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 12px 6px 16px;
}
.lbl-div--chip .lbl-div__chip {
    display: inline-block;
    background-color: color-mix(in srgb, var(--lbl-div-label-color, #888) 20%, transparent);
    padding: 2px 8px;
    border-radius: 999px;
    letter-spacing: 0.06em;
    font-size: calc(var(--lbl-div-font-size, 11px) - 1px);
    font-weight: 700;
}
.lbl-div--chip .lbl-div__line-thin {
    flex: 1;
    height: 1px;
    opacity: 0.5;
}

/* D \u2014 Underline only */
.lbl-div--underline { padding: 8px 16px 6px; }
.lbl-div--underline .lbl-div__label-underline {
    display: inline-block;
    border-bottom: 1px solid var(--lbl-div-line-color, #484848);
    padding-bottom: 3px;
}

/* E \u2014 Section header */
.lbl-div--section {
    position: relative;
    background-color: color-mix(in srgb, var(--lbl-div-label-color, #888) 10%, transparent);
    padding: 5px 12px 5px 14px;
    margin: 4px 0;
}
.lbl-div--section .lbl-div__bar {
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    width: 2px;
    background-color: var(--lbl-div-label-color, #888);
    border-radius: 0;
}
.lbl-div--section .lbl-div__label { font-weight: 700; }

/* F \u2014 Notion-style minimal */
.lbl-div--minimal { padding: 6px 0 4px; }
.lbl-div--minimal .lbl-div__label-soft {
    padding: 0 16px;
    font-weight: 500;
    opacity: 0.7;
    text-transform: none;
    letter-spacing: normal;
}
.lbl-div--minimal .lbl-div__line-soft {
    height: 1px;
    margin: 3px 12px 0;
    opacity: 0.4;
}

/* G \u2014 Bold accent + tucked label */
.lbl-div--tucked {
    position: relative;
    padding: 12px 12px 6px;
}
.lbl-div--tucked .lbl-div__label-tuck {
    position: absolute;
    top: -1px;
    right: 14px;
    font-size: calc(var(--lbl-div-font-size, 11px) - 1px);
    font-weight: 700;
    letter-spacing: 0.1em;
    background-color: var(--background-primary, var(--background-secondary, #1e1e1e));
    padding: 0 6px;
}
.lbl-div--tucked .lbl-div__line-thick {
    height: 2px;
    margin: 0 12px;
    background-color: var(--lbl-div-label-color, #888);
    opacity: 0.7;
}

/* H \u2014 Soft gradient bar */
.lbl-div--gradient {
    margin: 4px 0;
    padding: 5px 12px;
    background: linear-gradient(90deg,
        transparent 0%,
        color-mix(in srgb, var(--lbl-div-label-color, #888) 13%, transparent) 50%,
        transparent 100%);
    text-align: center;
}
.lbl-div--gradient .lbl-div__label-bar { letter-spacing: 0.1em; }
`;
  }
  /**
   * Remove every divider element this plugin has injected, plus its stylesheet.
   * Also scrubs the legacy pseudo-element residue from pre-1.3.0 versions in case
   * an existing install upgraded mid-session.
   */
  removeDividers() {
    document.querySelectorAll(".lbl-div").forEach((el) => el.remove());
    const styleEl = document.getElementById("lbl-div-styles");
    if (styleEl) styleEl.remove();
    const legacyStyles = document.getElementById("files-dividers-styles");
    if (legacyStyles) legacyStyles.remove();
    document.querySelectorAll("[data-item]").forEach((el) => {
      el.removeAttribute("data-item");
      el.removeAttribute("data-type");
      el.classList.remove(
        "nav-folder-divider-above",
        "nav-folder-divider-below",
        "nav-file-divider-above",
        "nav-file-divider-below"
      );
    });
  }
  toggleDividers() {
    this.settings.enabled = !this.settings.enabled;
    this.saveSettings();
    const status = this.settings.enabled ? "enabled" : "disabled";
    new import_obsidian.Notice(`Files dividers ${status}`);
  }
};
var FilesDividersSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Labeled Dividers" });
    new import_obsidian.Setting(containerEl).setName("Enable files dividers").setDesc("Turn dividers on or off globally for both files and folders").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Divider color").setDesc("Color of the divider lines").addColorPicker(
      (color) => color.setValue(this.plugin.settings.dividerColor).onChange(async (value) => {
        this.plugin.settings.dividerColor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Divider thickness").setDesc("Thickness of divider lines in pixels").addSlider(
      (slider) => slider.setLimits(1, 5, 1).setValue(this.plugin.settings.dividerThickness).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.dividerThickness = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Label styling" });
    new import_obsidian.Setting(containerEl).setName("Label color").setDesc("Color of section-label text on labeled dividers").addColorPicker(
      (color) => color.setValue(this.plugin.settings.labelColor).onChange(async (value) => {
        this.plugin.settings.labelColor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Label font size").setDesc("Size of label text in pixels").addSlider(
      (slider) => slider.setLimits(8, 18, 1).setValue(this.plugin.settings.labelFontSize).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.labelFontSize = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Uppercase labels").setDesc("Render labels in UPPERCASE with slight letter-spacing (section-header style)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.labelUppercase).onChange(async (value) => {
        this.plugin.settings.labelUppercase = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Bold labels").setDesc("Render label text in bold weight").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.labelBold).onChange(async (value) => {
        this.plugin.settings.labelBold = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Italic labels").setDesc("Render label text in italics").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.labelItalic).onChange(async (value) => {
        this.plugin.settings.labelItalic = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "How to use" });
    containerEl.createEl("p", {
      text: 'Right-click any file or folder in the file explorer. Pick "Add divider above/below" for a plain line, or "Add labeled divider above/below\u2026" to attach a section name. Labels render as small section-header text with a line beneath (or above, if positioned below).'
    });
    containerEl.createEl("h3", { text: "Current Dividers" });
    if (this.plugin.settings.dividers.length === 0) {
      containerEl.createEl("p", {
        text: "No dividers configured. Right-click on files or folders to add dividers.",
        cls: "setting-item-description"
      });
    } else {
      const folderDividers = this.plugin.settings.dividers.filter((d) => d.itemType === "folder");
      const fileDividers = this.plugin.settings.dividers.filter((d) => d.itemType === "file");
      const renderDividerRow = (divider, emoji) => {
        var _a;
        const labelDisplay = divider.label ? `"${divider.label}"` : "(no label)";
        const styleDisplay = divider.label ? ` \xB7 ${(_a = divider.labelStyle) != null ? _a : "above"}` : "";
        const setting = new import_obsidian.Setting(containerEl).setName(`${emoji} ${divider.itemName}`).setDesc(`Divider ${divider.position} \u2014 ${labelDisplay}${styleDisplay}`);
        setting.addText(
          (text) => {
            var _a2;
            return text.setPlaceholder("Section label (blank for plain line)").setValue((_a2 = divider.label) != null ? _a2 : "").onChange(async (value) => {
              this.plugin.updateDividerLabel(divider.itemName, divider.itemType, divider.position, value);
            });
          }
        );
        if (divider.label) {
          setting.addDropdown(
            (dropdown) => {
              var _a2;
              LABEL_STYLE_OPTIONS.forEach((opt) => {
                dropdown.addOption(opt.value, `${opt.letter} \u2014 ${opt.title}`);
              });
              dropdown.setValue((_a2 = divider.labelStyle) != null ? _a2 : "above").onChange(async (value) => {
                this.plugin.updateDividerStyle(divider.itemName, divider.itemType, divider.position, value);
                this.display();
              });
            }
          );
        }
        setting.addButton(
          (button) => button.setButtonText("Remove").setWarning().onClick(async () => {
            const globalIndex = this.plugin.settings.dividers.indexOf(divider);
            this.plugin.settings.dividers.splice(globalIndex, 1);
            await this.plugin.saveSettings();
            this.display();
          })
        );
        const advancedRow = containerEl.createDiv();
        advancedRow.style.display = "flex";
        advancedRow.style.gap = "12px";
        advancedRow.style.alignItems = "center";
        advancedRow.style.fontSize = "12px";
        advancedRow.style.opacity = "0.75";
        advancedRow.style.marginBottom = "14px";
        advancedRow.style.marginLeft = "24px";
        const labelColorWrap = advancedRow.createDiv();
        labelColorWrap.style.display = "flex";
        labelColorWrap.style.alignItems = "center";
        labelColorWrap.style.gap = "4px";
        labelColorWrap.createSpan({ text: "Label color override:" });
        const labelColorInput = labelColorWrap.createEl("input", { type: "color" });
        labelColorInput.value = divider.labelColor || this.plugin.settings.labelColor;
        labelColorInput.title = divider.labelColor ? "Override active \u2014 clear to use global" : "Using global color";
        labelColorInput.addEventListener("change", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "labelColor", labelColorInput.value);
        });
        const labelClearBtn = labelColorWrap.createEl("button", { text: "\xD7" });
        labelClearBtn.title = "Clear override (use global label color)";
        labelClearBtn.style.padding = "0 6px";
        labelClearBtn.style.minHeight = "0";
        labelClearBtn.addEventListener("click", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "labelColor", null);
          this.display();
        });
        const lineColorWrap = advancedRow.createDiv();
        lineColorWrap.style.display = "flex";
        lineColorWrap.style.alignItems = "center";
        lineColorWrap.style.gap = "4px";
        lineColorWrap.createSpan({ text: "Line color override:" });
        const lineColorInput = lineColorWrap.createEl("input", { type: "color" });
        lineColorInput.value = divider.lineColor || this.plugin.settings.dividerColor;
        lineColorInput.title = divider.lineColor ? "Override active \u2014 clear to use global" : "Using global color";
        lineColorInput.addEventListener("change", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "lineColor", lineColorInput.value);
        });
        const lineClearBtn = lineColorWrap.createEl("button", { text: "\xD7" });
        lineClearBtn.title = "Clear override (use global line color)";
        lineClearBtn.style.padding = "0 6px";
        lineClearBtn.style.minHeight = "0";
        lineClearBtn.addEventListener("click", async () => {
          this.plugin.updateDividerColor(divider.itemName, divider.itemType, divider.position, "lineColor", null);
          this.display();
        });
      };
      if (folderDividers.length > 0) {
        containerEl.createEl("h4", { text: "Folder Dividers" });
        folderDividers.forEach((divider) => renderDividerRow(divider, "\u{1F4C1}"));
      }
      if (fileDividers.length > 0) {
        containerEl.createEl("h4", { text: "File Dividers" });
        fileDividers.forEach((divider) => renderDividerRow(divider, "\u{1F4C4}"));
      }
      new import_obsidian.Setting(containerEl).addButton(
        (button) => button.setButtonText("Clear all dividers").setWarning().onClick(async () => {
          this.plugin.clearAllDividers();
          this.display();
        })
      );
    }
  }
};
var LabelInputModal = class extends import_obsidian.Modal {
  constructor(app, initialValue, initialStyle, callback) {
    super(app);
    this.settled = false;
    this.initialValue = initialValue;
    this.initialStyle = initialStyle;
    this.chosenStyle = initialStyle;
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Section label" });
    contentEl.createEl("p", {
      text: "Enter the section text. Leave blank to cancel.",
      cls: "setting-item-description"
    });
    const input = contentEl.createEl("input", { type: "text" });
    input.value = this.initialValue;
    input.placeholder = "e.g. PROJECTS";
    input.style.width = "100%";
    input.style.marginBottom = "12px";
    const styleLabel = contentEl.createEl("div", { text: "Label style" });
    styleLabel.style.fontWeight = "500";
    styleLabel.style.marginBottom = "4px";
    const styleRow = contentEl.createDiv();
    styleRow.style.display = "grid";
    styleRow.style.gridTemplateColumns = "1fr 1fr";
    styleRow.style.gap = "8px 16px";
    styleRow.style.marginBottom = "14px";
    const makeRadio = (value, letter, labelText, descText) => {
      const wrap = styleRow.createEl("label");
      wrap.style.display = "flex";
      wrap.style.alignItems = "flex-start";
      wrap.style.gap = "6px";
      wrap.style.cursor = "pointer";
      const radio = wrap.createEl("input", { type: "radio" });
      radio.name = "labeled-divider-style";
      radio.value = value;
      radio.checked = this.chosenStyle === value;
      radio.addEventListener("change", () => {
        if (radio.checked) this.chosenStyle = value;
      });
      const labelWrap = wrap.createDiv();
      const titleEl = labelWrap.createEl("div", { text: `${letter} \u2014 ${labelText}` });
      titleEl.style.fontSize = "13px";
      const descEl = labelWrap.createEl("div", { text: descText });
      descEl.style.fontSize = "11px";
      descEl.style.opacity = "0.7";
    };
    LABEL_STYLE_OPTIONS.forEach((opt) => {
      makeRadio(opt.value, opt.letter, opt.title, opt.desc);
    });
    const buttonRow = contentEl.createDiv();
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "flex-end";
    buttonRow.style.gap = "8px";
    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    const submitBtn = buttonRow.createEl("button", { text: "Add divider", cls: "mod-cta" });
    input.focus();
    input.select();
    const submit = () => {
      const value = input.value.trim();
      if (!value) {
        this.settle(null);
      } else {
        this.settle(value);
      }
      this.close();
    };
    const cancel = () => {
      this.settle(null);
      this.close();
    };
    submitBtn.addEventListener("click", submit);
    cancelBtn.addEventListener("click", cancel);
    input.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        evt.preventDefault();
        submit();
      } else if (evt.key === "Escape") {
        evt.preventDefault();
        cancel();
      }
    });
  }
  onClose() {
    if (!this.settled) {
      this.callback(null, this.chosenStyle);
      this.settled = true;
    }
    this.contentEl.empty();
  }
  settle(value) {
    if (this.settled) return;
    this.settled = true;
    this.callback(value, this.chosenStyle);
  }
};
